version: "3"

services:
  web:
    container_name: web
    build: .
    ports:
      - 5309:5309
    volumes:
      - .:/usr/src/app
    tty: true
  db:
    container_name: db
    image: mysql:5.7.24
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
