version: "3"

services:
  web:
    build: .
    container_name: mendrek
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_DATABASE: mendrek
      DB_HOST: db
      DB_PASSWORD: mendrek
      DB_USERNAME: mendrek
      NODE_ENV: development
      SPOTIFY_CLIENT_ID: ~
      SPOTIFY_CLIENT_SECRET: ~
    ports:
      - 5309:5309
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
  db:
    command: "--default-authentication-plugin=mysql_native_password --sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'"
    container_name: mendrek_db
    image: mysql:5.7.24
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: {}
